// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/27/2025, 2:28:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquisabah/Documents/msc-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/plugins/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/msc-admin/composables/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/msc-admin/utils/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/msc-admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/msc-admin/app.config.{js,ts,mjs}","/Users/marquisabah/Documents/msc-admin/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;