export const useProducts = () => {
  return [
    {
      id: 1,
      name: "IBUTEN 400",
      brand: "UniCure",
      description: "Ibuprofen 200mg tablets for pain and inflammation relief",
      category: "Pain Relief",
      image: "/img/a1.jpg",
      inStock: true,
      prescription: false,
    },
    {
      id: 2,
      name: "Luthermin Injection",
      brand: "UniCure",
      description: "Artemether + Lumefantrine antimalarial combination therapy",
      category: "Antimalarial",
      image: "/img/a2.jpg",
      inStock: true,
      prescription: true,
    },
    {
      id: 3,
      name: "Plumal",
      brand: "Unique Pharmaceuticals",
      description: "Artemether injection for severe malaria treatment",
      category: "Antimalarial",
      image: "/img/a3.jpg",
      inStock: true,
      prescription: true,
    },
    {
      id: 4,
      name: "Artexaten",
      brand: "UniCure",
      description: "Plumal 30 for anti-inflammatory pain relief",
      category: "Supplements",
      image: "/img/a4.jpg",
      inStock: true,
      prescription: false,
    },
    {
      id: 5,
      name: "Curefenac 100",
      brand: "UniCure",
      description:
        "Curefenac 100 for stomach acid relief and digestive comfort",
      category: "Gastroenterology",
      image: "/img/a5.jpg",
      inStock: true,
      prescription: false,
    },
    {
      id: 6,
      name: "Nophanix",
      brand: "UniCure",
      description: "Nophanix for inflammation and immune disorders",
      category: "Corticosteroids",
      image: "/img/a6.jpg",
      inStock: true,
      prescription: true,
    },
    {
      id: 7,
      name: "Curefenac Forte",
      brand: "UniCure",
      description:
        "Curefenac Forte tablets for inflammation and immune disorders",
      category: "Diabetes",
      image: "/img/a7.jpg",
      inStock: true,
      prescription: true,
    },
    {
      id: 8,
      name: "CureCee Vitamin C",
      brand: "UniCure",
      description:
        "CureCee Vitamin C tablets for inflammation and immune disorders",
      category: "Allergy",
      image: "/img/a8.jpg",
      inStock: true,
      prescription: true,
    },
    {
      id: 9,
      name: "Alminocure",
      brand: "UniCure",
      description: "Curefenac 50 tablets for inflammation and immune disorders",
      category: "Cardiovascular",
      image: "/img/a9.jpg",
      inStock: true,
      prescription: true,
    },
    {
      id: 10,
      name: "Kemal",
      brand: "UniCure",
      description: "Bisacure tablets for inflammation and immune disorders",
      category: "Antibiotics",
      image: "/img/a10.jpg",
      inStock: true,
      prescription: true,
    },
  ];
};
